baseUrl = "https://aayushshah.com.np/"
title = "Aayush Shah Kanu"

theme = "terminal"

languageCode = "en"
defaultContentLanguage = "en"

paginate = 5

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

enableEmoji = true

# Enable Disqus comments
disqusShortname = "Aayush shah"

# Enable Google Analytics
googleAnalytics = "G-Z2BNT5TQSP"

# Enable robots.txt
enableRobotsTXT = true

# To enable inline assets
enableInlineShortcodes = true

[params]
    author = "Aayush Shah Kanu"
    description = "I am a computer engineering undergrad studying at the Institute of Engineering, Pulchowk Campus. I am currently in the post of Software Coordinator in LOCUS. I am interested in Artificial Intelligence, Machine Learning, Computer Vision, and Natural Language Processing"
    keywords = "blog,developer,portfolio,tech,otaku"
    info = "Full Stack Developer, Deep Learning Enthusiast"
    avatarUrl = "images/cover.jpg"
    images = ["images/cover.jpg"]

    dateFormat = "February 2, 2022"

    since = 2022

    # Enable the Right To Left mode.
    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false

    # Series see also post count
    maxSeeAlsoItems = 5
    
    fullWidthTheme = false
    centerTheme = true

    # Enable Twemoji
    enableTwemoji = false

    # Custom CSS
    customCSS = ["css/academicons.css"]

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []


# If you want to implement a Content-Security-Policy, add this section
# NOTE: The work is tedius since add the sources have to be added
# [params.csp]
# 	  childsrc = ["'self'"]
# 	  fontsrc = [
#         "'self'",
# 		    "https://fonts.gstatic.com",
# 		    "https://cdn.jsdelivr.net/"
#     ]
# 	  formaction = ["'self'"]
# 	  framesrc = ["'self'"]
# 	  imgsrc = ["'self'"]
# 	  objectsrc = ["'none'"]
# 	  stylesrc = [
#         "'self'",
# 		    "'unsafe-inline'",
# 		    "https://fonts.googleapis.com/",
# 		    "https://cdn.jsdelivr.net/"
#     ]
# 	  scriptsrc = [
#         "'self'",
# 		    "'unsafe-inline'",
#             "https://ajax.cloudflare.com",
#             "https://static.cloudflareinsights.com",
#             "https://www.google-analytics.com",
#             "https://cdn.jsdelivr.net/"
#     ]
# 	  prefetchsrc = ["'self'"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Email"
    icon = "fa fa-send fa-2x"
    weight = 1
    url = "mailto:aayushshahkanu@gmail.com"
[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 2
    url = "https://github.com/aayushshah196/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin fa-2x"
    weight = 5
    url = "https://www.linkedin.com/in/aayush-shah-kanu-3b04401a2"


[languages]
    [languages.en]
        languageName = ":us:"
        title = "Aayush Shah Kanu"
        subtitle = "aayush"
        owner = "Aayush Shah Kanu"
        keywords = "blog,developer,otaku"
        copyright = "© 2022 Aayush Shah Kanu"
        
        menuMore = "Show more"
        readMore = "Read more"
        readOtherPosts = "Read other posts"

        [languages.en.params.logo]
            logoText = "HOME"
            logoHomeLink = "/about"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            identifier = "about"
            weight = 1
            url = "/about"

            [[languages.en.menu.main]]
            name = "CV"
            identifier = "cv"
            weight = 2
            url = "/cv"

            [[languages.en.menu.main]]
            name = "Blog"
            identifier = "posts"
            weight = 3
            url = "/posts"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
